# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 18:45
from __future__ import unicode_literals

from django.db import migrations
from django.template.defaultfilters import slugify


def get_slug(apps, schema_editor):
    Article = apps.get_model('news', 'Article')
    for row in Article.objects.all():
        row.slug = slugify(row.title)
        row.save()


class Migration(migrations.Migration):
    dependencies = [
        ('news', '0002_article_slug'),
    ]

    operations = [
        migrations.RunPython(get_slug, reverse_code=migrations.RunPython.noop)
    ]
