# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('news', '0003_auto_20160925_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
