# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 12:46
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('news', '0004_auto_20160925_0145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('news_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Article')),
            ],
            options={
                'ordering': ['-published'],
            },
        ),
    ]
