# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 06:34
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('news', '0007_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='news.Category'),
            preserve_default=False,
        ),
    ]
