# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 06:15
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0009_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reviewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='comment_reviewer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='reviewer_comment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[(b'NEW', b'New'), (b'APP', b'Approved'), (b'REJ', b'Rejected')],
                                   default=b'NEW', max_length=3),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
