# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 09:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_contentmanagercategories'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContentManagerCategories',
            new_name='ContentManagerCategory',
        ),
    ]
