# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 14:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_auto_20160928_1647'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='contentmanagercategory',
            options={'verbose_name': 'Content manager category', 'verbose_name_plural': 'Content manager categories'},
        ),
    ]
